### ISSUE TITLE
Onboard Georgiana to work on Pilot Hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#105]
Similar to https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/39, part of https://github.com/2i2c-org/pilot-hubs/issues/103.

Let's get @GeorgianaElena on boarded to how the pilot hubs work!

- [x] Add to GCP projects
- [x] Add to Auth0 project
- [x] Test drive getting kubectl / helm access (Following #104)
- [x] Test modifying image and pushing it through
- [x] Walk through the deployment script, documenting it as we go (https://github.com/2i2c-org/pilot-hubs/issues/110 maybe?)
- [x] Modify the JupyterHub templates (https://github.com/2i2c-org/pilot-hubs/issues/46 maybe?)
- [x] Do lots of code review

**Comment by GeorgianaElena** [comment]
I should already have access to the GCP projects. I'll go ahead and try the steps in #104 now :rocket: 
Are the pilot-hubs part of the 2i2c project (on GCP) or the other one with a long name? :sweat_smile: ?

**Comment by yuvipanda** [comment]
@GeorgianaElena \o/

So pilot hubs is part of `two-eye-two-see`, and the cloudbank hubs are part of the `cb-<whatever>` project. Should be documented in #104.

**Comment by GeorgianaElena** [comment]
Update: current step (3 and a half :sweat_smile: ): 

- [1/2] Test modifying image and pushing it through:
     - partially successful (ran into some permission issues when trying to push the image)

**Comment by GeorgianaElena** [comment]
@yuvipanda, I opened https://github.com/2i2c-org/pilot-homepage/pull/2 to address #46, but wasn't able to test it with the config in the `pilot-homepage` repo (there is more info in the PR).

**Comment by yuvipanda** [comment]
She's onboarded & kickinass :)
