### ISSUE TITLE
Create a plan to track hub onboarding, running hubs, and to-do items

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#220]
# Background

We need a pipeline / workflow around deploying, customizing, and operating new hubs. This should ensure that:

- Hubs that need action are addressed quickly
- That the hub infrastructure is stable across all hubs (e.g., downtime is minimized)
- That any support promises we made can be fulfilled (e.g., responses to issues etc)
- That this work is distributed in an equitable fashion amongst 2i2c team members
- That this is sustainable for us

# ToDo

- [ ] Define the process from "this person wants a hub" to "we now have a hub running". (see https://github.com/2i2c-org/pilot-hubs/issues/218 for one pattern we could use)
- [ ] Define where we keep track of running hubs, important metadata about them, and conversation about them amongst ourselves and between us and the users (@yuvipanda mentioned that GitHub issues may not be optimal, so we should explore other ideas!)
- [ ] Define a process for how 2i2c engineers keep tabs on "to do" items for the hubs, and how they divide labor in tackling them
