### ISSUE TITLE
Create Azure deployment infrastructure

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#373]
# Summary

We currently focus much of our deployment infrastructure around Google Cloud rather than AWS or Azure. We also have a few clients that would like their hubs working on Azure. We should improve our Azure deployment infrastructure and use these use-cases as forcing functions.

The use-case we can use for this is:

- The Justice Innovation Lab hub: https://github.com/2i2c-org/pilot-hubs/issues/288

The hub is currently running on Google Cloud, but they'd like us to move it to Azure whenever possible.

# Acceptance criteria

We should be able to spin up an Pangeo-style hub on Azure with the same ease that we currently have with GKE.

# Tasks to complete

- [ ] Move Azure terraform code to this repositor: https://github.com/2i2c-org/pilot-hubs/issues/512
- [ ] Get deployment scripts in this repo to work with Azure
- [ ] Move over the JIL to this infrastructure https://github.com/2i2c-org/pilot-hubs/issues/288

**Comment by yuvipanda** [comment]
We have a lot of Azure automation at github.com/utoronto-2i2c/jupyterhub-deploy/. https://github.com/utoronto-2i2c/jupyterhub-deploy/tree/staging/terraform has terraform for setting up an AKS based Kubernetes cluster with autoscaling, image repositories and an NFS server in the correct network (via ansible), and there's automated deployment with hubploy and github actions.

**Comment by choldgraf** [comment]
@yuvipanda thanks for that info! I've added a task to the top of the list to look into those repositories for inspiration

**Comment by choldgraf** [comment]
Now that the JIL is up and running, is this mostly an issue for *documentation* rather than building the infrastructure itself?

**Comment by yuvipanda** [comment]
@choldgraf so #287 hasn't been merged (or marked for review) yet. I think once that's done this will be an issue of documentation

**Comment by damianavila** [comment]
@choldgraf #287 was indeed merged but the work @yuvipanda is talking about lives in #513 AFAIK, am I correct @yuvipanda?

**Comment by yuvipanda** [comment]
At this point, I think https://github.com/2i2c-org/pilot-hubs/issues/512 and this issue completely overlap - so I'm going to close this one and develop that one.
