### ISSUE TITLE
Simpler sign-on process for demo hub

### ISSUE THREAD

**Issue by sean-morris** [2i2c-org/pilot-hubs#403]
# Summary

There is a conversation between Eric V, Yuvi and myself regarding allowing a simpler login process to the [demo hub](demo.cloudbank.2i2c.cloud) for instructors who are wanting to explore how the 2i2c hubs are working. 

# User Stories

- Currently, the [demo hub](demo.cloudbank.2i2c.cloud) is configured to use google-oauth2 which, of course, requires a google account to use. This can be a bit ackward when a potential instructor's work email address is not associated with Google. We are wanting to enable logging into the demo hub with a username and password(possibly default password) for a user who wants to see the hub in action. This is how the [workshop datahub](https://workshop.datahub.berkeley.edu/) is working. 

# Acceptance criteria

-  I assume acceptance is a consensus moment about moving forward from the group. Once we are finished, anyone can "log" into the demo hub with any username and a default password.

# Important information

- [Demo hub](demo.cloudbank.2i2c.cloud)
- [Workshop datahub](https://workshop.datahub.berkeley.edu/)

# Tasks to complete

- [ ] Discuss / decide on whether or not this is the way forward
- [ ]  Implement the change to the demo hub
- [ ] Re-deploy demo hub

**Comment by yuvipanda** [comment]
The berkeley workshop hub uses DummayAuthenticator with a simple password. It has restrictions on maximum active users as a way to control cost. I propose we do the same here.

**Comment by yuvipanda** [comment]
This is also just for demo.cloudbank.2i2c.cloud, so will mostly just be used by DSEP folks.

**Comment by choldgraf** [comment]
Fine with me - we can always change the password if people are abusing it. I think this hub should generally be "no promises" from us anyway

**Comment by yuvipanda** [comment]
ok I've actually instead added a signup with username / password + login there.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/30430/118560359-fe025b00-b786-11eb-940a-db1357c04801.png">


This uses auth0 as well - https://auth0.com/docs/connections/database.

@ericvd-ucb @sean-morris Once we switch, users who are currently using the google auth will need to sign up with a username / password to log in. Do you think you can communicate this to them?

**Comment by yuvipanda** [comment]
Documentation at pilot.2i2c.org also needs to be updated
