### ISSUE TITLE
Hub Engineer guide documentation v1

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#596]
# Summary

Our infrastructure has grown in complexity over the last few months, and we've also had an opportunity to onboard several new team members. We've written some documentation in this process to help one another learn how to operate the infrastructure, but there likely a major "documentation push" we'll need to complete at the beginning in order to ensure we have captured the major ideas. This is a tracking issue for the "1.0" status of our team infrastructure documentation.

# User Stories

- As a 2i2c team member, I want to be able to quickly learn how to carry out the workflows that are needed to operate and develop our hub infrastructure.
- As a stakeholder using a 2i2c Hub, I want to know that 2i2c's engineering team is well-organized and follows best practices for running cloud infrastructure.

# Acceptance criteria

We should re-assess the state of our Hub Engineer's / infrastructure guide around Q4 2021 and decide if it:

- Accurately reflects our infrastructure setup
- Has enough information that a new team member knows how to begin working on any of our hub infrastructure

# Tasks to complete

- [ ] Re-brand as the "Hub Engineer Guide" and re-factor sections to use top-level "topic areas"
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/156
- [ ] https://github.com/2i2c-org/team-compass/issues/127
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/302
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/351
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/504
- [ ] https://github.com/2i2c-org/team-compass/issues/171
- [ ] https://github.com/2i2c-org/team-compass/issues/128
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/590
- [x] https://github.com/2i2c-org/pilot-hubs/issues/568
- [ ] https://github.com/2i2c-org/meta/issues/69
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/431
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/210

**Comment by choldgraf** [comment]
Am going to keep track of these over here instead of in this big issue: https://github.com/orgs/2i2c-org/projects/18
