### ISSUE TITLE
Staging Hub deployment for Pangeo

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#599]
### Description

We should deploy a **staging hub** for Pangeo that has the same infrastructure setup on less-costly infrastructure. This may also generate some other tasks that we need to accomplish in order to get the base infrastructure running.

### Benefit

This will help us iterate more quickly and get feedback from the Pangeo team. It will also be a place where we can stage changes in the future without affecting `prod`, since Pangeo is a more complex and dynamic setup than most of our community hubs.

### Tasks to complete

- [x] Create initial staging deployment
  - [x] Figure out NFS configuration: https://github.com/2i2c-org/pilot-hubs/issues/599#issuecomment-903860481 
- [x] Merge in #597 
- [ ] https://github.com/2i2c-org/pilot-hubs/pull/651
- [ ] Iterate with feedback from @rabernat 
  - [x] Choices for session types: https://github.com/2i2c-org/pilot-hubs/issues/599#issuecomment-911597920
- [ ] Confirm that major functionality works as expected

  

---

### Updates

- 2021-08-24: We've got a hub deployed but the user servers aren't being created properly due to some NFS errors. We've agreed to **try fixing this for two weeks** (@yuvipanda will give this a shot). If we cannot fix it after that time, we will:
  - Re-deploy the Pangeo hub using Google File Storage
  - Track the deployment of in-cluster NFS as a separate enhancement here: #50  
- 2021-08-31: in the sprint planning meeting today, we discussed that, now that NFS is ready to go (#50) we should be ready to review this PR and merge it in, and then ask Pangeo folks to take a look at the hub and make sure it looks good. In a future step, we will finish up #598 and deploy it, but that's not necessary for the initial deployment

**Comment by sgibson91** [comment]
I've deployed a hub... sort of. k8s isn't able to mount the NFS server and I'm not sure if it's because I missed a step or because of the private cluster https://github.com/2i2c-org/pilot-hubs/pull/597#issuecomment-896684098

**Comment by choldgraf** [comment]
I believe this is no longer blocked. Now we need to have a team discussion about whether the NFS strategy used in the PR is the right strategy to use in general. I've updated this issue to mark it as-such. Check out @sgibson91's main question here:

https://github.com/2i2c-org/pilot-hubs/pull/597#issuecomment-900363440

**Comment by sgibson91** [comment]
This could use some discussion too https://github.com/2i2c-org/pilot-hubs/pull/597#issuecomment-900363440

**Comment by sgibson91** [comment]
A staging hub exists https://staging.pangeo.2i2c.cloud/

But spawning of the user server fails which means the NFS still needs some tweaking. Not sure if that needs to happen in #597 or #613

**Comment by choldgraf** [comment]
congrats @sgibson91 :-) 🚀

**Comment by sgibson91** [comment]
The first thing that needs to be done is fixing the spawn failure https://github.com/2i2c-org/pilot-hubs/pull/597#issuecomment-903865009

There's some discussion going on here about behaviour, but I think that needs a decision before it can be implemented https://github.com/2i2c-org/pilot-hubs/pull/597#issuecomment-902753175

**Comment by choldgraf** [comment]
**update**: in the sprint planning meeting today, we discussed that, now that NFS is ready to go (#50) we should be ready to review this PR and merge it in, and then ask Pangeo folks to take a look at the hub and make sure it looks good.

In a future step, we will finish up #598 and deploy it, but that's not necessary for the initial deployment

**Comment by yuvipanda** [comment]
This actually fails (it didn't used to!)
```
2021-09-01T21:38:01Z [Warning] MountVolume.SetUp failed for volume "pvc-958d82c1-5383-45e1-85e8-011091b2ae0f" : mount failed: exit status 1 Mounting command: /home/kubernetes/containerized_mounter/mounter Mounting arguments: mount -t nfs -o noatime,soft,vers=4.2 10.12.4.188:/export/pvc-958d82c1-5383-45e1-85e8-011091b2ae0f /var/lib/kubelet/pods/faeae25f-2156-4322-b6d4-cd00c438821b/volumes/kubernetes.io~nfs/pvc-958d82c1-5383-45e1-85e8-011091b2ae0f Output: Mount failed: mount failed: exit status 32 Mounting command: chroot Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs -o noatime,soft,vers=4.2 10.12.4.188:/export/pvc-958d82c1-5383-45e1-85e8-011091b2ae0f /var/lib/kubelet/pods/faeae25f-2156-4322-b6d4-cd00c438821b/volumes/kubernetes.io~nfs/pvc-958d82c1-5383-45e1-85e8-011091b2ae0f] Output: mount.nfs: mounting 10.12.4.188:/export/pvc-958d82c1-5383-45e1-85e8-011091b2ae0f failed, reason given by server: No such file or directory 
```

Trying to `deploy-support` fails with:

```
Error: UPGRADE FAILED: cannot patch "support-nfs-server-provisioner" with kind StatefulSet: StatefulSet.apps "support-nfs-server-provisioner" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

I think our timebox for using google file store expired, so i'm going to abandon in-cluster NFS and go that way.

**Comment by rabernat** [comment]
Thanks so much for all the hard work here!

After Yuvi's ping on Slack, I just tried logging in. I clicked login and got redirected to authorize a new github app (iam-login-something). Once redirected back to `https://staging.pangeo.2i2c.cloud/hub/oauth_callback?code=...`, I got met with 

> **403 : Forbidden**
>
> If your email address has NOT been added to the list of allowed users for this hub, please contact the hub administrators.

![image](https://user-images.githubusercontent.com/1197350/131765848-1e6b1ac0-e342-428c-b82e-907758636e22.png)

Our previous cluster was configured to allow all users from the group https://github.com/orgs/pangeo-data/teams/us-central1-b-gcp to be able to log in. It would be great to use that same group here.

Let me know how I can help.

**Comment by choldgraf** [comment]
@rabernat just a note that we are tracking the GitHub teams auth here: #598

**Comment by yuvipanda** [comment]
@rabernat try now

**Comment by rabernat** [comment]
Ok so I will continue to post feedback on this issue, as suggested by Chris.

Item 1: _There are no choices of machine type on startup_. Compare this to the [Profile List](https://github.com/pangeo-data/pangeo-cloud-federation/blob/d051d1829aeb303d321dd483450146891f67a93c/deployments/gcp-uscentral1b/config/common.yaml#L76-L117) on https://us-central1-b.gcp.pangeo.io/. This is important because some users (like my class) just need a small machine while others (like researchers) need lots of memory.

**Comment by rabernat** [comment]
Item 2: _My home directory is not there._ It would be great if we could migrate over the home directories from the old cluster. Since both clusters are using GC Filestore, perhaps this is trivial: just mount the same volume on the new cluster. But since it lives in a different project, maybe that doesn't work.

**Comment by rabernat** [comment]
Item 3: _Hub is not configured for requester-pays access to cloud data._ 

I discovered this by running the first few cells of [this notebook](http://gallery.pangeo.io/repos/pangeo-gallery/physical-oceanography/01_sea-surface-height.html), specifically

```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
ds  = cat["sea_surface_height"].to_dask()
```

raises
```
OSError: Forbidden: https://storage.googleapis.com/download/storage/v1/b/pangeo-cmems-duacs/o/.zmetadata?alt=media
Caller does not have serviceusage.services.use access to the Google Cloud project.
```

**Comment by choldgraf** [comment]
I'll try to capture some of @rabernat's suggestions in subsequent issues so that we don't lose track of them.

Note that when I try to log-in I'm running into a "scale-up" error:

![image](https://user-images.githubusercontent.com/1839645/131897981-63d7c861-a0ce-4ea9-9469-af91dcfd8963.png)

**Comment by choldgraf** [comment]
Another note - if I go to `Services -> Dask Gateway` (https://staging.pangeo.2i2c.cloud/services/dask-gateway/) then I get a blank page with `404 Not Found`.

**Comment by yuvipanda** [comment]
@choldgraf ah, the second smallest one works for me. Let's isolate and tweak the sizes until they all work. Can we use https://github.com/2i2c-org/pilot-hubs/issues/652 to track and close this?

**Comment by choldgraf** [comment]
@yuvipanda sounds good - I think that once https://github.com/2i2c-org/pilot-hubs/pull/651 is merged we can consider this one closed, and can then focus on specific improvements to the staging hub in separate issues
