### ISSUE TITLE
Status Page for our clusters

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#608]
# Summary

There are many cases where our clusters might be down for one reason or another (e.g. upgrades, outages, etc). In those cases, it's helpful if there is a source of truth for "is 2i2c's infrastructure down, or is it just me?". We should have a place to point users to so that they can quickly answer this question.

# Important information

The most common service I've seen for this is [`statuspage.io`](https://www.atlassian.com/software/statuspage), which [even has a non-profit discount](https://support.atlassian.com/statuspage/docs/apply-for-a-community-open-source-or-academic-license/).

# Tasks to complete

- [ ] Decide what kind of service we'd like to use for a status page
- [ ] ...figure out steps to implement this
- [ ] Document the new status page in our user and team documentation

**Comment by choldgraf** [comment]
Opening this issue so that we can track it, but setting priority to low right now because I don't think it's a critical issue currently

**Comment by choldgraf** [comment]
oops - closing since it's a dupe of https://github.com/2i2c-org/pilot-hubs/issues/609
