### ISSUE TITLE
Infrastructure Professionalization for the Managed JupyterHub Service v1

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#611]
# Summary

We need our Managed JupyterHub Service to reach a certain level of professionalization before we can consider it "production ready". This includes having a sound architectural design, robust deployment infrastructure, and a reliable experience in deploying all the kinds of hubs we wish to deploy.

# Benefit

The reason to focus explicitly on professionalization is so that we do not lose time in the future doing random de-bugs and putting out fires because our infrastructure is not working as expected. It is an intentional investment of our time now in order to avoid unintentionally spending a lot of our time on operations work in the future.

# Acceptance criteria

We'll need to decide as a team what "good enough" looks like here. I'd suggest something like:

Each member of the Engineering team is confident that they could deploy all of our hubs on their own, that the hubs would operate as-expected without issue, and that we feel confident telling Hub Administrators to use our hubs for important work.

# Tasks to complete

- [x] https://github.com/2i2c-org/pilot-hubs/issues/336
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/507
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/577
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/586
- [x] https://github.com/2i2c-org/pilot-hubs/issues/518
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/502
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/452
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/449
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/279
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/152
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/165
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/616
- [ ] https://github.com/2i2c-org/team-compass/issues/228
- [ ] ...add tasks here as we think they fit under this goal

**Comment by choldgraf** [comment]
I'm closing this as Yuvi included much of these in #610
