### ISSUE TITLE
Automate building and pushing images for users with repo2docker action

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#630]
# Summary

Users should ideally have full control over the images their hub runs. Setting up GitHub repositories with automatic building via GitHub actions + [repo2docker-action](https://github.com/jupyterhub/repo2docker-action) is the best way to do this. It sticks to standards, plus people can test out their image on mybinder.org!

# Tasks

We need a couple new features in repo2docker-action for this to fully work.

- [x] #631
- [x] Support pushing to multiple registries https://github.com/jupyterhub/repo2docker-action/issues/70
- [x] Complete https://github.com/jupyterhub/repo2docker-action/issues/65 and make sure that it is possible to do this via the action
- [x] Update our documentation to highlight this pattern, pointing to repo2docker action docs for the details
  - [x] the template repository created by #631 
  - [x] the pilot documentation` (maybe around here: https://pilot.2i2c.org/en/latest/admin/howto/environment.html#customize-your-hub-environment)
- [ ] Documentation in repo2docker-action
  - [ ] Add documentation about pushing to GCR, GAR and Azure container registry instructions in https://github.com/jupyterhub/repo2docker-action/issues/61 :arrow_right: https://github.com/jupyterhub/repo2docker-action/pull/80
- [ ] 2i2c-specific documentation about this :arrow_right: https://github.com/2i2c-org/hub-user-image-template/pull/4
  - [ ] Mention in the template repository that there are multiple registries they can push to, then point people to the repo2docker-action for the actual docs
  - [ ] Mention that for cloud provider-specific registries, if we are running the cluster on our projects, then we'll need to give you credentials for it

**Comment by choldgraf** [comment]
In today's sprint meeting we decided to try and finish this one up this week, but if @GeorgianaElena runs into any snags in the coming days, we should re-assess and decide to re-scope. Our current thinking is that this one is now mostly a matter of documentation and figuring out the right pattern, but we might be wrong there!

**Comment by choldgraf** [comment]
hey @GeorgianaElena where are we on this one? maybe at tomorrow's sprint meeting we can discuss what are the next steps to close this one out.
