### ISSUE TITLE
Create a template repo + documentation for hub user image repos

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#631]
### Description

Many of our hubs are using a dedicated repository to define, build, and push the user image for the repo. This is a useful pattern, and we should document and make it easier for others to follow this pattern.

Some repositories that do this:

- https://github.com/2i2c-org/coessing-image
- https://github.com/2i2c-org/openscapes-image

Ultimately users should be able to do the following:

- Clone a template repo
- Modify it slightly to define the environment they want, per instructions in the repository's README
- Use the repo2docker action to build and push and image of the repository
- Connect their hub to the image for use in the hub via the configurator

This should be the default for any hub that wants to use its own image!

This issue should focus on using **quay.io** as the image registry, we can tackle other registries later!

### Benefit

This would benefit many communities who wish to maintain their own user image (this is probably most communities!) and would also benefit the 2i2c Engineer team because we'll have less toil to do in updating minor changes to images.

### Implementation

We should start off with just a simple repository structure, that has the proper GitHub actions scripts and a simple `environment.yml` file that others can copy.

For more advanced use-cases (like using a Dockerfile) we can add documentation that tells people what to do in the README, but don't need to bake it into the repository's structure.

### Tasks to complete

- [x] Create a template git repo with repo2docker-action support and pushing to `quay.io` :arrow_right: https://github.com/2i2c-org/hub-user-image-template
- [x] Centralize user documentation: :arrow_right: https://github.com/2i2c-org/hub-user-image-template/pull/1
       -  on how to add packages / test changes to the repo 
       - on how they can change their hub's image with the configurator
- [ ] Reference this new user documentation from [`pilot/`](https://pilot.2i2c.org/en/latest/)

**Comment by choldgraf** [comment]
Now that we have https://github.com/2i2c-org/hub-user-image-template/pull/1 I think the only other thing we need to do is include some documentation about this in `pilot/` and then we are good to go 🚀
