### ISSUE TITLE
Automatically deploy carbonplan hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#632]
### Description

Currently when you change things in pilot-hubs, it doesn't actually update CarbonPlan's hub. We should build auto-deployment infrastructure instead.

Was tried in https://github.com/yuvipanda/pilot-hubs/commit/f687264dadad5d126f3e281fa22c87d39dba8b17 but reverted, as the auth provided by the checked-in kubeconfig is not enough. We need https://github.com/2i2c-org/pilot-hubs/issues/381 with eks support to be able to deploy automatically from CI

### Tasks

- [x] Get @damianavila access to work on this hub
- [x] Create an AWS user with credentials setup with access to the EKS cluster
- [x] Add support to our deployer to fetch k8s credentials from eks (porting [this code](https://github.com/yuvipanda/hubploy/blob/dfc00254abb30d8887230472e83b405ff5872933/hubploy/auth.py#L298))
- [ ] Deploy changes whenever a change is merged here

**Comment by yuvipanda** [comment]
@damianavila what's your carbonplan AWS username? I can give you access to the EKS cluster by following https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

**Comment by damianavila** [comment]
> @damianavila what's your carbonplan AWS username? 

I have pinged you in Slack with that info :wink: .

**Comment by yuvipanda** [comment]
@damianavila I added you to list of users who can access the EKS cluster, with

`eksctl create iamidentitymapping -f carbonplan.yaml --group system:masters --username admin --arn arn:aws:iam::631969445205:user/damian`

**Comment by damianavila** [comment]
> Add support to our deployer to fetch k8s credentials from eks (porting this code)

Update: Draft PR #636 tries to deal with this item.

**Comment by damianavila** [comment]
Update:

* Created a `deployer` user in the AWS carbonplan space under the 2i2c group.
* Added the identity mapping for that new `deployer` user so it can access the EKS cluster
* Got access keys for that user and encrypted them

Tested manually (after some adjusting in the logic) and it seems to be working as expected.

**Comment by damianavila** [comment]
Some commands I have used for the above update:

* Create a new user:
`aws iam create-user --user-name deployer`

* Add the user to the 2i2c group
`aws iam add-user-to-group --group-name 2i2c --user-name deployer`

* Check if the user was added to the group
`aws iam get-group --group-name 2i2c`

* Get the credentials:
`aws iam create-access-key --user-name deployer | tee /tmp/deployer.json`

* Add the user to the EKS cluster
`eksctl create iamidentitymapping --cluster carbonplanhub --region=us-west-2 --arn arn:aws:iam::631969445205:user/deployer --group system:masters --username admin`

* Check if the user was added to the map
`eksctl get iamidentitymapping --cluster carbonplanhub --region=us-west-2`

**Comment by damianavila** [comment]
For posterity, this one was deployed successfully after merging it: https://github.com/2i2c-org/pilot-hubs/runs/3533569179?check_suite_focus=true
