### ISSUE TITLE
Improve the "Add a new hub" documentation

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#646]
### Description

Currently we have relatively sparse documentation for adding a new hub. It is located here:

https://pilot-hubs.2i2c.org/en/latest/howto/operate/new-hub/index.html

We should include a few extra pieces of information that are important:

- A high level overview of what happens when we add a new hub
- The difference between adding a hub to an existing cluster, vs. creating a new cluster for a hub
- The difference between a manual deploy and an automatic deploy
- When adding a hub is expected to be "easy" vs. difficult.
- Some kind of decision tree workflow to follow for people

### Value / benefit

This would make it easier to know what to expect when deploying a hub, which will help us understand what kind of hubs we can easily deploy for others. It will also help us standardize knowledge across the team about what deploying a hub entails, and it will highlight areas where we need to make improvements.

### Implementation details

We should update the pilot documentation here:

https://pilot-hubs.2i2c.org/en/latest/howto/operate/new-hub/index.html

This might also be a good opportunity to run a link-check (https://github.com/2i2c-org/pilot/issues/76) and potentially some other documentation features.

### Tasks to complete

- [ ] Update the documentation at https://pilot-hubs.2i2c.org/en/latest/howto/operate/new-hub/index.html
- [x] Do https://github.com/2i2c-org/pilot/issues/76 at the same time
- [ ] Make other documentation improvements if they don't increase the scope too badly
