### ISSUE TITLE
Prepare Pangeo Hub for Ryan's course

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/pilot-hubs#652]
### Description

I am hoping to use the new 2i2c Pangeo hub (see #599) for my fall Research Computing course. My ~20 students will be logging in for the first time on **Sept. 14**. It would be really great if they could log in to the new hub, rather than the old one.

**If we miss this deadline**

Ryan will need to use the pre-existing Pangeo Hub, then either

- Migrate students over mid semester
- Keep operating the old Pangeo hub until December

### Value / benefit

I will personally benefit as the instructor of my course.

Pangeo users will benefit from the upgraded environment.

2i2c will benefit by wrapping up this project, freeing staff to focus on other things.

### Implementation details

We'll tackle this by first ensuring that our **staging cluster** is set up with the environment, infrastructure, etc needed for @rabernat's course. We need to do this by getting feedback from him about what needs to be updated or changed, and then fixing up those issues in the task list below.

The staging hub lives at:

staging.pangeo.2i2c.cloud

Once we get the staging hub "ready to go", our next step will be to deploy a **production hub** that mimics the staging hub in its configuration. This will be the hub that we point Ryan and his students to. We can then continue improving and iterating in staging over the coming weeks.

### Tasks to complete

- [x] Staging cluster customized for Ryan's course
  - [x] Recent `pangeo-notebook` image
  - [x] Profile list that allows users to choose between different memory / CPU (https://github.com/2i2c-org/pilot-hubs/issues/599#issuecomment-911597920)
  - [x] Get feedback from @rabernat and iterate on Staging as necessary
  - [x] https://github.com/2i2c-org/pilot-hubs/issues/661
  - [x] https://github.com/2i2c-org/pilot-hubs/issues/655
- [x] Deploy production cluster once staging is 👍 from ryan
  - [ ] Logins for all students (for now, we'll just manually add to the hub, see https://github.com/2i2c-org/pilot-hubs/issues/652#issuecomment-912038124)

edit: other issues that we had listed here are moved to this Project so that we don't lose track of them: https://github.com/orgs/2i2c-org/projects/16#card-68036583

### Updates

- **2021-09-07**: we decided to re-scope this issue to just include the things that are needed for this week's hub infrastructure, so that we make sure that we focus on that. We'll tackle the other improvements in subsequent weeks.

**Comment by yuvipanda** [comment]
@rabernat I've updated to latest notebook and added a set of CPU / RAM options.

**Comment by yuvipanda** [comment]
dask-gateway is already setup and should work the same as pangeo. Let's try it out?

**Comment by choldgraf** [comment]
Echoing what @yuvipanda said, I think that the easiest thing to do for authenticating the students will be to manually add them to the Hub's user list via the Admin UI, by [following these instructions](https://pilot.2i2c.org/en/latest/admin/howto/manage-users.html#manage-users-from-the-administrator-panel).

You might also consider adding a more trusted student / TA as an "Admin" user on the hub, so that they can add students as well.

This should be pretty easy to do for just 20 students. It won't scale but I hope that it would be an acceptable stop-gap. 

I think that means that the "only" thing that we need to do is make sure that the production hub setup works as expected.

**Comment by rabernat** [comment]
> I think that the easiest thing to do for authenticating the students will be to manually add them to the Hub's user list via the Admin UI

Yes I approve this suggestion and will do it. I will just need a mechanism to gather github usernames from the students, which I will figure out myself.

**Comment by choldgraf** [comment]
@rabernat you could probably add them to a GitHub Team "as if" we were using the proper teams-based authentication, and then just dump that list of usernames into the hub via the GitHub API (https://docs.github.com/en/rest/reference/teams#list-team-members)?

That way, when teams-based membership was possible you could just switch the auth setup and it would automatically work with the same group of people

**Comment by choldgraf** [comment]
**update**: I've created issues for each of the major items that @rabernat described above. I've also added them to a project here so that we don't lose track of them: https://github.com/orgs/2i2c-org/projects/16

Could we re-scope this issue to just the first task list, and remove the others that are "next up"? I want to make sure that we don't lose focus on the most important things here to prepare @rabernat for his class on September 14th.

**Comment by sgibson91** [comment]
Picking up #655 today

**Comment by rabernat** [comment]
Thanks to everyone working on this. I appreciate your efforts so much! 🤗 

I have played around with staging.pangeo.2i2c.cloud. 

- ✅  I tested that I could create, scale up, and scale down Dask Gateway clusters (xref #656)
- ✅  I ran some examples from Pangeo Gallery and they worked great! (xref #654)

While I wouldn't close those issues just yet, I am satisfied that the hub works as needed to get my course started.

_I would recommend to deploy the current config to production and then continue to iterate the other issues on staging._

**Comment by sgibson91** [comment]
@rabernat if you could let us know what days of the week and times your classes are, I'll try to avoid merges during class time. (While we can iterate on staging separately, anything that gets merged will be deployed to all hubs through CI - that's why I'm thinking about avoiding your classes.)

**Comment by rabernat** [comment]
Tuesday / Thurdsay 10am-11:30am ET.

However, the students may be using the hub at any hour of the day.

**Comment by sgibson91** [comment]
@rabernat new hub is available at prod.pangeo.2i2c.cloud

**Comment by sgibson91** [comment]
Reopening until we fix #677

**Comment by rabernat** [comment]
> new hub is available at prod.pangeo.2i2c.cloud

🎉  One small nit: could we just use the DNS name **pangeo.2i2c.cloud**?

**Comment by sgibson91** [comment]
When we _actually_ migrate, I was going to point the DNS the project is currently using anyway, so our *2i2c.cloud address won't matter. But we need a way to distinguish between the prod and staging hubs as traffic for both are going through the same load balancer, and therefore the same IP address. So the short answer is, I don't think we can do that/I'm not sure of a way to do that given how our infrastructure is setup.

**Comment by yuvipanda** [comment]
@sgibson91 if we create a DNS A record for pangeo.2i2c.cloud pointing to the IP, it should 'just work', regardless of the entry on staging.pangeo.2i2c.cloud.

**Comment by rabernat** [comment]
Ok, this is not a dealbreaker, but just from a technical perspective, my understanding was that `staging.pangeo.2i2c.cloud` and `pangeo.2i2c.cloud` are distinct, fully qualified DNS names, so it should be possible.

**Comment by sgibson91** [comment]
I'll see if I have time to get to it after firefighting #677

**Comment by sgibson91** [comment]
The dedicated node pools are now up and working, and the hub is available at https://pangeo.2i2c.cloud

**Comment by rabernat** [comment]
At the pangeo meeting today @sgibson91's update reminded me that I have not yet shared the following message.

:tada: :tada: **Everything is working great with the new hub!** :tada: :tada:

Thanks so much for your work pushing this forward. I sincerely appreciate the efforts on a tight timeline.

**Comment by choldgraf** [comment]
wohoo! I indeed was wondering this haha. @sgibson91 thanks so much for all of your hard work :-)

**Comment by rabernat** [comment]
Sorry for not posting earlier. Been swamped with actually teaching the class. Can you get the hub to do that part too? 😆

**Comment by choldgraf** [comment]
It would not surprise me if @sgibson91 knew how to write a GitHub action that both teaches your class and writes a grant for you 🙂
