### ISSUE TITLE
Can't spin up a small machine on Pangeo staging hub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#661]
### Description

I was working on #655 and wanted to login to the staging hub in order to test if I had successfully granted access to the Pangeo requestor-pays data. From the profile list I selected "small machine", but my server never comes up.

Error logs from the JupyterHub page:

<img width="797" alt="Screenshot 2021-09-07 at 13 14 57" src="https://user-images.githubusercontent.com/44771837/132342772-e28a2df3-db09-4c2c-8551-0ad32b9d0e92.png">

<details><summary>Output of `kubectl describe pod jupyter-sgibson91`</summary>

```bash
Name:                 jupyter-sgibson91
Namespace:            staging
Priority:             0
Priority Class Name:  staging-default-priority
Node:                 <none>
Labels:               app=jupyterhub
                      chart=jupyterhub-1.1.3
                      component=singleuser-server
                      heritage=jupyterhub
                      hub.jupyter.org/network-access-hub=true
                      hub.jupyter.org/network-access-proxy-http=true
                      hub.jupyter.org/servername=
                      hub.jupyter.org/username=sgibson91
                      release=staging
Annotations:          hub.jupyter.org/username: sgibson91
Status:               Pending
IP:                   
IPs:                  <none>
Init Containers:
  volume-mount-ownership-fix:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan
    Environment:  <none>
    Mounts:
      /home/jovyan from home (rw,path="sgibson91")
      /var/run/secrets/kubernetes.io/serviceaccount from user-sa-token-mxwp5 (ro)
Containers:
  notebook:
    Image:      pangeo/pangeo-notebook:bcfacc5
    Port:       8888/TCP
    Host Port:  0/TCP
    Args:
      jupyterhub-singleuser
      --ip=0.0.0.0
      --port=8888
      --SingleUserNotebookApp.default_url=/lab
    Limits:
      cpu:     2
      memory:  8589934592
    Requests:
      cpu:     1
      memory:  5905580032
    Environment:
      CPU_GUARANTEE:                          1.0
      CPU_LIMIT:                              2.0
      DASK_GATEWAY__ADDRESS:                  http://proxy-public/services/dask-gateway
      DASK_GATEWAY__AUTH__TYPE:               jupyterhub
      DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE:  {JUPYTER_IMAGE_SPEC}
      DASK_GATEWAY__PROXY_ADDRESS:            gateway://traefik-staging-dask-gateway.staging:80
      DASK_GATEWAY__PUBLIC_ADDRESS:           /services/dask-gateway/
      JPY_API_TOKEN:                          2e1b1dd265ce40c0a7cdc598867fee0e
      JUPYTERHUB_ACTIVITY_URL:                http://hub:8081/hub/api/users/sgibson91/activity
      JUPYTERHUB_ADMIN_ACCESS:                1
      JUPYTERHUB_API_TOKEN:                   2e1b1dd265ce40c0a7cdc598867fee0e
      JUPYTERHUB_API_URL:                     http://hub:8081/hub/api
      JUPYTERHUB_BASE_URL:                    /
      JUPYTERHUB_CLIENT_ID:                   jupyterhub-user-sgibson91
      JUPYTERHUB_HOST:                        
      JUPYTERHUB_OAUTH_CALLBACK_URL:          /user/sgibson91/oauth_callback
      JUPYTERHUB_SERVER_NAME:                 
      JUPYTERHUB_SERVICE_PREFIX:              /user/sgibson91/
      JUPYTERHUB_USER:                        sgibson91
      JUPYTER_IMAGE:                          pangeo/pangeo-notebook:bcfacc5
      JUPYTER_IMAGE_SPEC:                     pangeo/pangeo-notebook:bcfacc5
      MEM_GUARANTEE:                          5905580032
      MEM_LIMIT:                              8589934592
    Mounts:
      /home/jovyan from home (rw,path="sgibson91")
      /home/jovyan/shared from home (ro,path="_shared")
      /home/jovyan/shared-readwrite from home (rw,path="_shared")
      /usr/local/etc/jupyter/jupyter_notebook_config.json from files (rw,path="jupyter_notebook_config.json")
      /var/run/secrets/kubernetes.io/serviceaccount from user-sa-token-mxwp5 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  home-nfs
    ReadOnly:   false
  files:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  singleuser
    Optional:    false
  user-sa-token-mxwp5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  user-sa-token-mxwp5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node.kubernetes.io/instance-type=n1-standard-2
Tolerations:     hub.jupyter.org/dedicated=user:NoSchedule
                 hub.jupyter.org_dedicated=user:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason             Age    From                    Message
  ----     ------             ----   ----                    -------
  Warning  FailedScheduling   4m24s  staging-user-scheduler  0/2 nodes are available: 2 node(s) didn't match node selector.
  Warning  FailedScheduling   4m24s  staging-user-scheduler  0/2 nodes are available: 2 node(s) didn't match node selector.
  Normal   NotTriggerScaleUp  4m22s  cluster-autoscaler      pod didn't trigger scale-up: 4 node(s) had taint {k8s.dask.org_dedicated: worker}, that the pod didn't tolerate, 4 node(s) didn't match Pod's node affinity, 1 Insufficient memory
```
</details>

Also, the hub pod is having difficulty with its readiness probe for some reason.

<details><summary>Output of `kubectl describe pod hub-*`</summary>

```bash
Name:                 hub-766bbc7848-cm469
Namespace:            staging
Priority:             0
Priority Class Name:  staging-default-priority
Node:                 gke-pangeo-hubs-cluster-core-pool-b7fdb3c5-x0hz/10.128.0.23
Start Time:           Tue, 07 Sep 2021 13:20:05 +0100
Labels:               app=jupyterhub
                      component=hub
                      hub.jupyter.org/network-access-proxy-api=true
                      hub.jupyter.org/network-access-proxy-http=true
                      hub.jupyter.org/network-access-singleuser=true
                      pod-template-hash=766bbc7848
                      release=staging
Annotations:          checksum/config-map: 390369c2af173ec8d3c020b3c4c6718fc041fe7e9e565f65580c0e348c8d92fb
                      checksum/secret: 142644abf7719d61f74984c73a4c755a9a6b714dc2d9d6ae8085bdf6f61f8b5a
                      cni.projectcalico.org/podIP: 10.8.2.37/32
                      cni.projectcalico.org/podIPs: 10.8.2.37/32
Status:               Running
IP:                   10.8.2.37
IPs:
  IP:           10.8.2.37
Controlled By:  ReplicaSet/hub-766bbc7848
Init Containers:
  templates-clone:
    Container ID:  containerd://11b059c859c075b07394e2966970507e6f6dd9aad95bde31102e2427d20328df
    Image:         alpine/git
    Image ID:      docker.io/alpine/git@sha256:0590372ee83d4d0ff4f08f8d2a98b0ba413d911a2e89c1d3418a1fed9a66337c
    Port:          <none>
    Host Port:     <none>
    Args:
      clone
      --
      https://github.com/2i2c-org/pilot-homepage
      /srv/repo
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 07 Sep 2021 13:20:23 +0100
      Finished:     Tue, 07 Sep 2021 13:20:24 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /srv/repo from custom-templates (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-vf7lt (ro)
Containers:
  templates-sync:
    Container ID:  containerd://c46ec77698ac7d254fdbb967abf725132486738fb77de0e122a4c15d52d5f628
    Image:         alpine/git
    Image ID:      docker.io/alpine/git@sha256:0590372ee83d4d0ff4f08f8d2a98b0ba413d911a2e89c1d3418a1fed9a66337c
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do git fetch origin;
      if [[ $(git ls-remote --heads origin staging | wc -c) -ne 0 ]]; then
          git reset --hard origin/staging;
      else
          git reset --hard origin/master;
      fi
      sleep 5m; done
      
    State:          Running
      Started:      Tue, 07 Sep 2021 13:20:25 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /srv/repo from custom-templates (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-vf7lt (ro)
  hub:
    Container ID:  containerd://ccb3598fcc4ce99e7c09812425d4492c3b50803bfd4a20ac6c924dbf6ae8844c
    Image:         quay.io/2i2c/pilot-hub:0.0.1-n1159.h5b045cd
    Image ID:      quay.io/2i2c/pilot-hub@sha256:20c687d90c30c723c17e676ea32d84a093a4179da20d788f8f0184a38107da4d
    Port:          8081/TCP
    Host Port:     0/TCP
    Args:
      jupyterhub
      --config
      /usr/local/etc/jupyterhub/jupyterhub_config.py
      --upgrade-db
    State:          Running
      Started:      Tue, 07 Sep 2021 13:20:25 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  2Gi
    Requests:
      cpu:      10m
      memory:   128Mi
    Liveness:   http-get http://:http/hub/health delay=300s timeout=3s period=10s #success=1 #failure=30
    Readiness:  http-get http://:http/hub/health delay=0s timeout=1s period=2s #success=1 #failure=1000
    Environment:
      PYTHONUNBUFFERED:        1
      HELM_RELEASE_NAME:       staging
      POD_NAMESPACE:           staging (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'hub.config.ConfigurableHTTPProxy.auth_token' in secret 'hub'>  Optional: false
    Mounts:
      /srv/jupyterhub from pvc (rw)
      /usr/local/etc/jupyterhub-configurator/00-default.schema.json from files (rw,path="configurator-schema-default")
      /usr/local/etc/jupyterhub/config/ from config (rw)
      /usr/local/etc/jupyterhub/jupyterhub_config.py from config (rw,path="jupyterhub_config.py")
      /usr/local/etc/jupyterhub/secret/ from secret (rw)
      /usr/local/etc/jupyterhub/z2jh.py from config (rw,path="z2jh.py")
      /usr/local/share/jupyterhub/custom_templates from custom-templates (rw,path="templates")
      /usr/local/share/jupyterhub/static/extra-assets from custom-templates (rw,path="extra-assets")
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-vf7lt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hub
    Optional:  false
  secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub
    Optional:    false
  files:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub
    Optional:    false
  custom-templates:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  hub-db-dir
    ReadOnly:   false
  hub-token-vf7lt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-token-vf7lt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  hub.jupyter.org/node-purpose=core
Tolerations:     hub.jupyter.org/dedicated=core:NoSchedule
                 hub.jupyter.org_dedicated=core:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                From                                   Message
  ----     ------                  ----               ----                                   -------
  Normal   Scheduled               2m22s              gke.io/optimize-utilization-scheduler  Successfully assigned staging/hub-766bbc7848-cm469 to gke-pangeo-hubs-cluster-core-pool-b7fdb3c5-x0hz
  Normal   SuccessfulAttachVolume  2m11s              attachdetach-controller                AttachVolume.Attach succeeded for volume "pvc-22d5b3ad-6f0a-44ef-b306-0461f0928cb8"
  Normal   Pulling                 2m4s               kubelet                                Pulling image "alpine/git"
  Normal   Pulled                  2m4s               kubelet                                Successfully pulled image "alpine/git" in 127.33456ms
  Normal   Created                 2m4s               kubelet                                Created container templates-clone
  Normal   Started                 2m3s               kubelet                                Started container templates-clone
  Normal   Pulling                 2m3s               kubelet                                Pulling image "alpine/git"
  Normal   Pulled                  2m3s               kubelet                                Successfully pulled image "alpine/git" in 88.104644ms
  Normal   Created                 2m2s               kubelet                                Created container templates-sync
  Normal   Started                 2m2s               kubelet                                Started container templates-sync
  Normal   Pulled                  2m2s               kubelet                                Container image "quay.io/2i2c/pilot-hub:0.0.1-n1159.h5b045cd" already present on machine
  Normal   Created                 2m2s               kubelet                                Created container hub
  Normal   Started                 2m2s               kubelet                                Started container hub
  Warning  Unhealthy               112s (x5 over 2m)  kubelet                                Readiness probe failed: Get "http://10.8.2.37:8081/hub/health": dial tcp 10.8.2.37:8081: connect: connection refused

```
</details>

### Value / benefit

I will immediately benefit from being able to test if I have successfully granted access to requestor pays data.

Users of the hub (incl. production which will borrow from staging's config) will need to be able to spin up any machine in the profile list.

### Tasks to complete

- [ ] Check other machine sizes spin up ok
- [ ] Tweak nodeselector and memory request values to mitigate

### Updates

* The medium machine spins up fine and I was able to test the requestor pays stuff there

**Comment by sgibson91** [comment]
### Update

* The medium machine spins up fine and I was able to test the requestor pays stuff there

(I don't know why this isn't showing up at the bottom of the top comment btw. It's in the raw markdown 🤷🏻‍♀️)

**Comment by yuvipanda** [comment]
We match pods to nodepools based on node labels and memory capacity (https://github.com/2i2c-org/pilot-hubs/blob/2f4a68b68fe4277c4a58b2fbd9544568bf48f0d0/config/hubs/pangeo-hubs.cluster.yaml#L78), so only one pod ends up on a node (not helpful in edu contexts, but helpful in research contexts). We probably need to tweak the values for nodeselector and memory request so the autoscaler knows which nodepool to scale up.

**Comment by sgibson91** [comment]
### Tasks to complete

- [ ] Check other machine sizes spin up ok
- [ ] Tweak nodeselector and memory request values to mitigate

**Comment by rabernat** [comment]
Thanks for checking this Sarah! I just hit the same issue myself and was glad to see it was already on the radar.

As long as we are looking at the profile list, it would be nice to match the settings of the earlier cluster: https://github.com/pangeo-data/pangeo-cloud-federation/blob/d051d1829aeb303d321dd483450146891f67a93c/deployments/gcp-uscentral1b/config/common.yaml#L76-L105

I am concerned about the possible cost liabilities if we let anyone launch a notebook pod with 128 GB of RAM! Ideally we could differentiate the profile list based on user groups, but afaik this is not possible.

**Comment by sgibson91** [comment]
Thanks @rabernat - I will begin working on this today and I was indeed going to check what options where currently available on the old cluster :)

**Comment by sgibson91** [comment]
Confirming that changing the cpu/mem specs to match what is currently running on the old pangeo cluster (linked above in Ryan's comment) fixes this issue. I'm going to check everything else spins up ok and add in the ML option too.

**Comment by sgibson91** [comment]
@TomAugspurger do you mind giving me a little bit of insight into the nodepool machine types that the different profiles are assigned to when they're requested please? Poking around [here](https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/pangeo-uscentral1b/nodes?authuser=1&project=pangeo-181919) it seems to me everything is a `n1-highmem-4`?

**Comment by TomAugspurger** [comment]
I *think* the GCP hub is configured to use GKE's "node auto-provisioning": https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning. The basic idea is to create a node-pool on the fly based on the resource requests of the pod.

The only thing giving me pause is that the auto-provisioning stuff seems to be commented out in the Makefile (https://github.com/pangeo-data/pangeo-cloud-federation/blob/d051d1829aeb303d321dd483450146891f67a93c/deployments/gcp-uscentral1b/Makefile)
