### ISSUE TITLE
Collect data and assess node auto-provisioning on Pangeo cluster

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#671]
### Description

Following discussion in #666 we deployed node auto-provisioning on the Pangeo cluster in #670. This issue is to track the performance, cost-benefits, etc of using node auto-provisioning in this cluster and decide whether this is a feature we want to support long-term as an alternative to configuring node pools manually.

This is a time-boxed issue and we should aim to be making a decision within a 2-3 month time frame.

Some more context: https://github.com/2i2c-org/pilot-hubs/issues/666#issuecomment-915956414

### Value / benefit

✅ Node auto-provisioning would reduce 2i2c Engineer's manual interaction with the cluster
❌ It may not actually be that cost-effective

We don't know the answers to these q's until we gather data and analyse 🙂 

### Tasks to complete

- [ ] Decide what metrics we need to evaluate and what "success" or "failure" of those metrics looks like
- [ ] Decide what data will help towards evaluating those metrics
- [ ] Decide how that data should be collected
- [ ] Implement collection of data
- [ ] Analyse data and evaluate metrics
- [ ] Decide to support node auto-provisioning long-term or not

**Comment by choldgraf** [comment]
Updated to add the possibility of a little blog post at the end, after chatting about it with @sgibson91 :-)
