### ISSUE TITLE
[Hub Enhancement] - Install R geoscience packages for U. Toronto hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#697]
### Description

We have a request to add a number of new packages to the U. Toronto hub. These are designed for geospatial analytics.

Here's a quick list of the packages:

- rgeos
- rgdal
- raster
- rasterVis
- sp
- spdep
- gdistance
- sf
- stars
- ggplot2
- ggmap
- ggsn

### Value / benefit

This will allow a professor to run a geospatial analytics class on the Toronto hub

### Implementation details

The change will need to be in the UToronto deploy repository: https://github.com/utoronto-2i2c/jupyterhub-deploy

In addition, they provided a notebook that fails in the first cell in section 3, as an example of what is not working. Here’s the link with the github puller:

https://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fhhwagner1%2FBIO311_Labs&urlpath=tree%2FBIO311_Labs%2F&branch=main    

### Tasks to complete

- [x] https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/101
- [x] https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/114
- [x] https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/116

**Comment by choldgraf** [comment]
After merging, the image build failed, so we need to manually build and push. I don't believe I have the credentials (or the knowledge) to do this, so maybe @GeorgianaElena can give this a shot on Monday.

I opened an issue to track this: https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/114

also just a note, this person's course is on **Wednesday** and I think they'd really appreciate having these packages available before then.

**Comment by GeorgianaElena** [comment]
These packages are now in production https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/120. Thanks for deploying them @choldgraf.

Closing this one :tada:
