### ISSUE TITLE
Update U. Toronto credentials in the repository

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#702]
### Description

In https://github.com/2i2c-org/pilot-hubs/issues/637 needed to deploy new Auth credentials to the U. of Toronto JupyterHub.

Those are deployed on the hub, but not yet in our GitHub repository for the hub. We need to update that repository with the new credentials.

### Value / benefit

We cannot make any deploys using the utoronto hub at https://github.com/utoronto-2i2c/jupyterhub-deploy until this is done, because otherwise the old authentication credentials will be re-instated.

### Implementation details

From this comment (https://github.com/2i2c-org/pilot-hubs/issues/637#issuecomment-908635467) it looks like we need to update the AzureAdAuthenticator here: https://github.com/utoronto-2i2c/jupyterhub-deploy/blob/e1fd790000734f1356a5a78357ccca0df0d21f38/deployments/utoronto/secrets/prod.yaml#L20

I believe that @yuvipanda is the person that has the credentials we need.

### Tasks to complete

- [ ] Confirm that @yuvipanda has these credentials
- [ ] Encode with sops and push to the utoronto-deploy repo
- [ ] Try re-deploying to production (maybe using the same PR from #692) and confirm that the hub auth works as expected.

**Comment by choldgraf** [comment]
assigning @yuvipanda for now since he's (I think) the only one with these credentials...if he confirms that somebody else has them then others could give this a shot as well
