### ISSUE TITLE
Reduce costs on our GKE clusters by switching to n1 instances

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#715]
### Description

We currently use `e2` instances, which are lower cost in general but which do *not* give us "sustained use" discounts. While `n1` instances are generally more performant and costlier, they *do* allow for "sustained use" discounts, and so we will end up getting a cost savings if we switch to them.

- GCP machine types docs: https://cloud.google.com/compute/docs/machine-types
- GCP sustained use docs: https://cloud.google.com/compute/docs/sustained-use-discounts
- GCP machine costs: https://cloud.google.com/compute/vm-instance-pricing

Switching to n1 instances will give us pretty good cost savings.

### Value / benefit

From the [machine costs page](https://cloud.google.com/compute/vm-instance-pricing):

- `e2-highmem-4` costs $.18 / hour
- `n1-highmem-4` costs $.24 / hour
- `n1-highmem-4` at a 30% discount (assuming 100% use): ~$.16/hour

So it'd cost less to have a higher-performance machine.

### Implementation details

Doing this requires updating the terraform deployment configuration for our various hubs.

PR to track some of this is here: https://github.com/2i2c-org/pilot-hubs/pull/665

### Tasks to complete

- [ ] Agree on the cost savings described here
- [ ] Deploy changes to our clusters via terraform
- [ ] Update our terraform configuration files (https://github.com/2i2c-org/pilot-hubs/pull/665)

**Comment by choldgraf** [comment]
@yuvipanda could you check my math above for the example I provided for what kinds of cost-savings to expect? and am I correct that the main benefit is that the machines would be higher-performance even though the cost would be lower w/ the sustained use discount?

One question: it looks like N1 instances have less memory in general than E2 instances. Since our user nodes are generally RAM-limited, wouldn't this mean we can fit fewer users onto an N1 node in general?

**Comment by damianavila** [comment]
Even when this one was automatically closed by #665, I think some of the questions raised above by @choldgraf still need some answers, @yuvipanda 😉

**Comment by choldgraf** [comment]
@yuvipanda if you confirm my analysis in the top comment, and mention if there's anything major I am missing, then I'd be happy to turn this into a short blog post update for the 2i2c community

**Comment by yuvipanda** [comment]
> One question: it looks like N1 instances have less memory in general than E2 instances. Since our user nodes are generally RAM-limited, wouldn't this mean we can fit fewer users onto an N1 node in general?

Yes, but the amount of memory that is different is small enough to not have much of a significant difference.

I didn't check the numbers, but your description of what is happening is correct!

It was @consideRatio's post in https://github.com/jupyterhub/team-compass/issues/243#issuecomment-569162570 that convinced me a while ago that n1 instances are the way to go.

**Comment by consideRatio** [comment]
> I had just thought that it only applied if the same instance was on continuously - turns out that is not the case!

Oh it isn't the case!? How does it work? Is it checking for the minimum count of instance during some time or similar? If that is the case, then one should always use node surge when upgrading on GKE - because adding and then removing a node would not reduce the minimum count, while removing then adding would.

**Comment by yuvipanda** [comment]
@consideRatio see https://cloud.google.com/compute/docs/sustained-use-discounts#calculating_discounts?
