### ISSUE TITLE
Migrate Pangeo prod hub onto GitHub Teams authentication and coordinate with Comm. Reps.

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#733]
### Description

Upon merge of #726, 2i2c hubs now support using the native JupyterHub OAuthenticator to authenticate users against GitHub orgs/teams. #707 will enable authentication against the `pangeo-data/us-central1-b-gcp` GitHub Team on the Pangeo **staging** hub. We need to migrate the **prod** hub across as well but we need to coordinate with @rabernat as his class is currently using this hub so we need to make the transition as smooth as possible.

### Value / benefit

- Pangeo rely on the GitHub Teams method of authentication and this brings us one step closer to fully migrating over the userbase

### Implementation details

- Since we are still using GitHub handles for auth, this **should not** affect users home dirs

### Tasks to complete

- [ ] @rabernat to coordinate with his class to make sure they all join the `pangeo-data/us-central1-b-gcp` GitHub Team
- [ ] @rabernat confirms in this issue that his class is ready for the auth migration
- [ ] @sgibson91 opens a PR to update the `pangeo-hubs` config so that the staging and prod hubs share configuration, including auth and performs the upgrade
- [ ] @rabernat confirms a smooth transition 🤞🏻 (or not! 😬 )

**Comment by sgibson91** [comment]
@paigem This would be a great opportunity for users of the COESSING hub to begin preparing to [migrate to the Pangeo hub](https://github.com/2i2c-org/pilot-hubs/issues/679) too. They will also need to be members of the `pangeo-data/us-central1-b-gcp` team, but I believe there is a form where folk can sign up to be added. @rabernat could you share that form please?

**Comment by sgibson91** [comment]
Never mind, I found the sign up form! https://docs.google.com/forms/d/e/1FAIpQLSeqKncKG-s365pC_Lfe4_UetJ-wcFfjOSyHhYYQjXbKRHzswQ/viewform

**Comment by sgibson91** [comment]
> So if I understand this correctly, anyone from COESSING who wants to retain access to JupyterHub on the cloud will need to fill out the form that you linked above?

Correct. And for privacy's sake, Pangeo are the ones collecting this data, not 2i2c. https://pangeo.io/cloud.html#sign-up

> Will all of their files be automatically transferred, or should they download their notebooks locally?

They won't be there immediately and it certainly won't be happening automatically! I will be manually transferring the user directories across. This will be tracked in this issue https://github.com/2i2c-org/pilot-hubs/issues/653

There will be a gap between me migrating the data and the service being available for use which I will try to minimise to the best of my ability. I will also be making posts in the [Pangeo discourse forum](https://discourse.pangeo.io/) that will detail when the domain switch-over will take place and when the last data migration occurred before that date. If users are really worried about any work loss then they can certainly download their notebooks locally as a backup.

> Additionally, there are a few (mostly very small in size) datasets in the shared folder on the COESSING Hub. Will those be transferred ~~automatically~~ somehow, or should I provide other methods for folks to obtain that data?

**Comment by rabernat** [comment]
Today I invited everyone from the class to the GitHub team and announced that they need to accept the invite.

**Comment by sgibson91** [comment]
PR to make the switch is here: https://github.com/2i2c-org/infrastructure/pull/768
